version: '3.8'

services:
  frontend:
    image: objectdetection-reactfrontend
    ports:
      - "3000:3000"
    # Add other configuration options as needed

  backend:
    image: objectdetection-flaskapi
    ports:
      - "5000:5000"
    # Add other configuration options as needed

# Define a custom network for the services to communicate
networks:
  default:
    name: object_detection_network
